### PR TITLE
adding my blog

### PR DESCRIPTION
**Pull request by mahsakr**
to controbute into TheBlogChallenge, this change is for adding my blog.

### CODE REVIEW

**Review by Titan-Programmer — APPROVED** [review]
Excellent, well done.

Please feel free add additional to comments to the other tabs.

**Comment by mahsakr** [comment]
Sure thank you for accepting my request

**Comment by Titan-Programmer** [comment]
No problem at all. 

This challenge is designed to practice your Git skills on a live project.

**Comment by mahsakr** [comment]
I had another change in index.html, in the 3rd tab, but I can't see it. isn't it merged?

**Comment by Titan-Programmer** [comment]
Try clearing the web cache and refreshing the browser. I can certainly see the changes. 

The new comment should be at the bottom. 

Although, I'm going make changes soon to put all the newest comments at the top.

**Comment by mahsakr** [comment]
I got it, thank you

**Pull request merged**
